name: Run Python Script Daily

on:
  schedule:
    - cron: '* * * * *'  # This runs at 4:00 AM UTC every day

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If you have dependencies listed

      - name: Run script
        run: python main.py  # Replace with your script's filename
